
extends Node2D

class TopLevel:
	func init():
		pass
	
	func exit():
		pass
	


class AtkState:
	
	func init():
		pass
	
	func exit():
		pass

class AblState:
	
	func init():
		pass
	
	func exit():
		pass

class DefState:
	
	func init():
		pass
	
	func exit():
		pass

class FleeState:
	
	func init():
		pass
	
	func exit():
		pass

func _ready():
	# Called every time the node is added to the scene.
	# Initialization here
	pass


